### ISSUE TITLE
vgdmb... has changed

### ISSUE THREAD

**Issue by bridalstyle** [arbingordon/vgmdbrip#1]
We gotta get this thing working with the new vgmdb cookie system! The cookies referenced in the code don't exist anymore, LOL!

**Comment by arbingordon** [comment]
I fixed it locally but didn't figure anyone still used this.  I'll upload a fix shortly.

**Comment by arbingordon** [comment]
Actually, my fix was for something else - there is a new cookie system and it may take a bit to get the kinks worked out.

**Comment by bridalstyle** [comment]
The VGM gods have a special place in heaven for you!

**Comment by arbingordon** [comment]
Fixed dcf003cefbcca4f08386f0e2ed5b2eb76daad62f
