### ISSUE TITLE
changes on vgmdb? Script isn't working anymore.

### ISSUE THREAD

**Issue by kioshimushi** [arbingordon/vgmdbrip#2]
Since maybe a week or two, I can't make it work, maybe a change on vgmdb?

**Comment by arbingordon** [comment]
Their cert chain is broken:
`<Toad King> looks like the issue with vgmdb.net is that it doesn't supply its certificate chain correctly. so only apps that have the intermediate CA (DigiCert SHA2 Secure Server CA) stored work but places that only have root CA's do not`

In the short term, I'm disabling the cert verification, until they fix it.
I would avoid using this on starbucks wifi and the like.

**Comment by gigablah** [comment]
It's fixed now, thanks for reporting.
